name: Build the application
run-name: Building the application

on: 
  push:
    branches-ignore:
      - master
    paths-ignore:
      - .github/**
      - README.md
  pull_request:
    paths-ignore:
      - .github/**
      - README.md
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - closed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Build application
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event.pull_request.merged || github.event_name == 'workflow_dispatch' && true || false }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/team-draw:latest
          context: ${{ github.workspace }}          